iRobotEducation/create3_docs

docs/index.md
The previous links were returning 404 errors due to being absolute links
Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>
=> fix broken links in homepage

docs/hw/electrical.md
Removed colored circles since they are from different versions of the Unicode standard and also are not guaranteed to properly render. Also fixed text on yellow indicator. This fixes #24
=> Remove Unicode circles and fix yellow indicator text

docs/examples/create3_examples.md, docs/examples/overview.md, docs/setup/xml-config.md, mkdocs.yml
Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>
This PR contains the following changes:
- add network configuration page
- move the RPi and jetson setup pages under a "Setup Compute Boards" level to distinguish them from the robot setup.
- rephrase a little bit the Create 3 examples stub page
=> add xml-config page and move boards setup down one level

docs/hw/electrical.md
Confirmed that the battery needs to be reset after the BMS detects undervoltage before it will recharge in many cases.
Added a suggestion to power the robot down instead of having it die off the dock, leading to potential undervoltage.
=> Explicit warning about shutting off the robot and explain battery reset

docs/setup/pi4.md
Updating directions to install irobot_create_msgs and explicitly install rmw-cyclonedds-cpp from the package manager.
=> irobot_create_msgs no longer needs to be built

docs/setup/compute-ntp.md, docs/setup/multi-robot.md, docs/setup/pi4.md, docs/setup/provision.md, docs/setup/ubuntu2004.md, docs/setup/xml-config.md, mkdocs.yml
Removed a lot of information specific to Raspberry Pi and tested these directions with a VM on Windows. Short of OR improving their "not-Ubuntu" ROS 2 support, I think this will open doors for a lot of users.
=> Adding directions for install on a simple Ubuntu 20.04 machine

docs/setup/pi4.md, docs/setup/ubuntu2004.md
New users were copying in all of the lines of code at once and pasting them at once, which doesn't work. Hopefully this will stop them.
=> Split code blocks to stop people from ^C^V-ing them in at once

docs/setup/pi4.md
The old link points now to a 22.04 installation page.
I haven't been able to find a direct download link for 20.04 for RPi, the closest thing I found is this tutorial which uses the RPi imager and allows to choose between all available versions.
=> update link to install ubuntu 20.04 on RPi

docs/api/reflexes.md, docs/setup/jetson.md
fix copy paste typos in reflex docs and add instructions to install additional packages in jetson setup
Note:
some of these packages are definitely already present in the Jetson docker image, but for example the irobot_create_msgs are not.
better be safe than sorry and make sure that everything is installed
=> fix reflexes and update jetson setup

docs/hw/hookup.md, docs/hw/jetson_hookup.md, docs/hw/navqplus_hookup.md, docs/hw/rpi_hookup.md, mkdocs.yml
This is split out from a previous closed [PR 167](https://github.com/iRobotEducation/create3_docs/pull/167) and creates a cleaner layout for the connected compute boards.
=> Update board hookup organization.

docs/api/reflexes.md
In testing reflexes again, I found (and Erik confirmed) that there is a docs typo.
=> Fixing reflex parameters (should be "reflexes.*")

docs/setup/ubuntu2004.md, docs/setup/ubuntu2204.md, mkdocs.yml
This is a first pass at Humble on Ubuntu 22.04 instructions. I actually tested these on a Raspberry Pi 4, and if you all approve of this, I will use it to update the Raspberry Pi instructions. (I actually configured this SD card completely using the GUI Raspberry Pi flashing tool; the only option that is not there is setting up Ethernet gadget and the relevant networking.)
=> First pass at Humble on 22.04 directions

docs/setup/ubuntu2204.md
Since this install could potentially be for desktop as well as for server, it was suggested to change the link from a direct one to the ISO to the Ubuntu landing page, instead.
=> Change link for Ubuntu to landing page

docs/setup/ubuntu2204.md
For the Create 3 we should encourage users to load create3 messages, not have it buried at the end of a suggestion
=> Make adding create 3 messages a mandatory step rather than recommended

docs/setup/ubuntu2204.md
Had a user complain that the `ros2` command didn't work after following these directions. Sure enough, I forgot to instruct them to run /opt/ros/humble/setup.bash and friends.
=> Autorun some things on a new bash session

README.md
Fixes missing `install` command in the README for it to properly install the dependencies listed within other text files.
=> Add missing install command

docs/releases/g_5_2.md, docs/releases/h_1_1.md, docs/releases/h_1_2.md, docs/releases/h_2_1.md, docs/releases/h_2_2.md, docs/releases/overview.md, mkdocs.yml
This patch release reduces the CPU core utilization by 5% - 10% (for one test, median-mean of 9%, sampled over an hour).
=> Release G.5.2 and H.2.2

docs/setup/compute-ntp.md, docs/setup/pi4galactic.md, docs/setup/pi4humble.md
When going through the lidar demo, I also ran into #44. The issue was indeed a mismatch of timestamps on the raspi. From a vanilla Ubuntu Raspi Server install, there aren't any NTP servers defined for synchronization, so the timestamps on the raspi were something like Mar 2023 for me, but the robot timestamps were present day.
These changes walk through adding NTP servers during raspi setup, which should allow the raspi to sync its clock and be happy.
=> Add additional raspi3 setup instructions that fixes iRobotEducation/create3_examples#44

docs/hw/jetson_hookup.md, docs/releases/g_5_3.md, docs/releases/h_2_3.md, docs/releases/overview.md, mkdocs.yml
* Webserver
* Fix to the provisioning flow affecting some users ( fixes #395 )
* ntpd.conf is now reset upon factory reset.
* Publications
* The `cliff_intensity` topic will no longer report values less than zero.
* The `kidnap_status` timestamp is now correct.
=> Release G.5.3 & H.2.3

docs/setup/ubuntu2204.md
Fresh copies of Ubuntu 22.04 desktop do not have curl pre-installed. Added instructions to install curl before authorizing the Open Robotics GPG key. This is consistent with the Galatic instructions that have users installing curl in prior steps.
=> Add instruction to install curl

docs/hw/electrical.md, docs/hw/face.md, docs/hw/overview.md, docs/releases/g_5_4.md, docs/releases/h_2_4.md, docs/releases/overview.md, docs/stylesheets/irobot-palette.css, docs/webserver/forget-wifi.md, mkdocs.yml
* Add beta feature to disconnect from wlan0 and forget the SSID (#110)
* Robot will now change its light ring to "spinning red" when the battery level dips below 3%, and will explicitly call the /robot_power service when it falls below 2%.
* The /rotate_angle action no longer accepts overriding goals; an ongoing goal must be completed (successfully or unsuccessfully) before a new goal will be accepted. (#351)
* Improve reliability of robot docking and undocking.
=> Release G.5.4 / H.2.4

docs/api/docking.md, docs/api/moving-the-robot.md, docs/api/wall-follow.md, mkdocs.yml
This PR improves the documentation on how to move the robot and adds a disclaimer for wall-follow.
See related forum discussions: https://github.com/iRobotEducation/create3_docs/discussions/511 and https://github.com/iRobotEducation/create3_docs/discussions/516
FYI @slowrunner
=> Improve `cmd_vel` and wall-follow docs

docs/releases/h_2_6.md, docs/releases/overview.md, mkdocs.yml
Bugfix release!
Robot now sets `max_speed` parameter properly when `safety_override = full` is set in application configuration ( closes #558 )
=> Release H.2.6

docs/releases/i_0_0.md, docs/releases/overview.md, docs/setup/xml-config.md, docs/webserver/application.md, mkdocs.yml
For ROS 2[^1] users, this is a feature release, and our first upgrade to ROS 2 Iron.
For iRobot® Education Bluetooth[^2] users, there are no changes.
See below for details.
Note: In testing, this release appears to be fully compatible with ROS 2 Jazzy, as well. Please be sure to let us know if you run into any [issues](https://github.com/iRobotEducation/create3_docs/issues).
* Topics
* The robot can now be tele-operated via `geometry_msgs/msg/TwistStamped` messages on the `cmd_vel_stamped` topic. (You may also continue to use the `cmd_vel` topic; don't use both at the same time.)
[^1]: ROS 2 is governed by Open Robotics.
[^2]: The Bluetooth® word mark and logos are registered trademarks owned by Bluetooth SIG, Inc. and any use of such marks by iRobot is under license.
[^3]: All other …
=> Release I.0.0
